# -*- coding: utf-8 -*-
"""Qrcode_Generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12lQu0dfM21dFHUlqVLJNuvo9DtX1fc4E
"""

!pip install qrcode

import qrcode

qr=qrcode.QRCode( version=1,
                 box_size=10,
                 border=5
    )

data="Welcome_/\_ _/\_ Namaskara"

qr.add_data(data)
qr.make(fit=True)

img=qr.make_image(fill="black", back_color="white")

img.save("hello.png")